2021-03-14T15:00:25.1626725+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-03-14T15:00:25.1949837+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-03-14T15:00:25.1966527+01:00  [INF] Content root path: "C:\Users\jasie\source\repos\CarTryApplicationMVC\CarTryApplicationMVC.Web" (b5d60022)
2021-03-14T15:00:25.3198480+01:00 80000018-0003-fc00-b63f-84710c7967bb [INF] Jestem, w Home/Index (55499141)
2021-03-14T15:00:50.1738887+01:00 80000030-000b-ff00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at CarTryApplicationMVC.Application.Service.CustomerService.GetCustomerDetail(Int32 customerId) in C:\Users\jasie\source\repos\CarTryApplicationMVC\CarTryApplicationMVC.Application\Service\CustomerService.cs:line 70
   at CarTryApplicationMVC.Web.Controllers.CustomerController.CustomerDetail(Int32 id) in C:\Users\jasie\source\repos\CarTryApplicationMVC\CarTryApplicationMVC.Web\Controllers\CustomerController.cs:line 88
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-03-14T15:07:39.9361808+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-03-14T15:07:39.9462766+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-03-14T15:07:39.9479412+01:00  [INF] Content root path: "C:\Users\jasie\source\repos\CarTryApplicationMVC\CarTryApplicationMVC.Web" (b5d60022)
2021-03-14T15:07:40.0505571+01:00 80000078-0008-ff00-b63f-84710c7967bb [INF] Jestem, w Home/Index (55499141)
2021-03-14T15:08:51.0794630+01:00 800000a2-0000-ff00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at CarTryApplicationMVC.Application.Service.CustomerService.GetCustomerDetail(Int32 customerId) in C:\Users\jasie\source\repos\CarTryApplicationMVC\CarTryApplicationMVC.Application\Service\CustomerService.cs:line 70
   at CarTryApplicationMVC.Web.Controllers.CustomerController.CustomerDetail(Int32 id) in C:\Users\jasie\source\repos\CarTryApplicationMVC\CarTryApplicationMVC.Web\Controllers\CustomerController.cs:line 88
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-03-14T15:09:07.3364964+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-03-14T15:09:07.3457956+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-03-14T15:09:07.3472719+01:00  [INF] Content root path: "C:\Users\jasie\source\repos\CarTryApplicationMVC\CarTryApplicationMVC.Web" (b5d60022)
2021-03-14T15:09:07.4411279+01:00 80000022-0007-ff00-b63f-84710c7967bb [INF] Jestem, w Home/Index (55499141)
2021-03-14T15:11:13.3109555+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-03-14T15:11:13.3215606+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-03-14T15:11:13.3231229+01:00  [INF] Content root path: "C:\Users\jasie\source\repos\CarTryApplicationMVC\CarTryApplicationMVC.Web" (b5d60022)
2021-03-14T15:11:13.4257452+01:00 80000082-0006-ff00-b63f-84710c7967bb [INF] Jestem, w Home/Index (55499141)
